### PR TITLE
[ass] Update dependencies to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by jlaine**
- update ass to 0.15.2 (requires harfbuzz)

### CODE REVIEW

**Comment by jlaine** [comment]
I have no idea what's going on here. For some reason `libass` is not picking up the freetype we built..

**Comment by wqh17101** [comment]
@jlaine As a matter of experience，maybe you should export PKG_CONFIG_PATH such as `PKG_CONFIG_PATH=/usr/local/lib:/usr/lib64:$PKG_CONFIG_PATH` .Then pkg-config will find the lib.

**Comment by jlaine** [comment]
We do already set PKG_CONFIG_PATH see https://github.com/PyAV-Org/pyav-ffmpeg/blob/main/scripts/cibuildpkg.py#L358

**Comment by wqh17101** [comment]
Also i see that you build so for all dependencies,may LD_LIBRARY_PATH and `ldconfig` is needed.

**Comment by wqh17101** [comment]
I found that it happened when build fontconfig, and i use `export PKG_CONFIG_PATH=/tmp/vendor/lib/pkgconfig:$PKG_CONFIG_PATH` to fix it.
It can build normally now.

**Comment by wqh17101** [comment]
I am not sure that the error happened when building harfbuzz.Becasue i build harfbuzz successfully

**Comment by wqh17101** [comment]
The first time i met `FREETYPE no` is the moument i built fontconfig for i did not install `pkg-config`.
My pkg-config`s version is 0.29.1

**Comment by wqh17101** [comment]
@jlaine Another suggestion is that when downloading source code, the file name wil be {version}.tar.gz sometimes, it is better to rename it to a uniform name to avoid some conflicts for the same version of different dependencies.

**Comment by jlaine** [comment]
The problem seems to be that Centos 7 (the distro mandated for manylinux2014 wheels) carries too old a version of pkg-config. harfbuzz seems to require pkg-config >= 0.28, but we have 0.27.1.

**Comment by wqh17101** [comment]
Maybe update freetype at the same time?
https://freetype.org/ for the latest is 2.11.1

**Comment by jlaine** [comment]
Nope, updating freetype breaks the build, rolling back.

**Comment by wqh17101** [comment]
> Nope, updating freetype breaks the build, rolling back.

Fine, just waiting until it is necessary to update

**Pull request merged**
