### PR TITLE
Build FFmpeg for aarch64

### PR DESCRIPTION
**Pull request by jlaine**

### CODE REVIEW

**Comment by jlaine** [comment]
@odidev would you have any pointers on how to get this working?

I'm hitting two issues:

- the build is so slow I hit github actions' 6 hour limit
- if I use "parallel" make (make -j) it looks like I hit an OOM error

**Comment by odidev** [comment]
@jlaine, due to qemu emulation, AArch64 build is slower. The "multi-stage" approach is complicated but unfortunately we don't have any other way as GHA don't provide AArch64 agents/builders.

If you are ok to manage another CI for AArch64, you can try CircleCI which provides free aarch64 builders. Let me know if you need any help from myside?

**Comment by jlaine** [comment]
> @jlaine, due to qemu emulation, AArch64 build is slower. The "multi-stage" approach is complicated but unfortunately we don't have any other way as GHA don't provide AArch64 agents/builders.
> 
> If you are ok to manage another CI for AArch64, you can try CircleCI which provides free aarch64 builders. Let me know if you need any help from myside?

Hi! I think I don't have a choice, I'm getting nowhere on Github actions for aarch64. I would appreciate some guidance as I tried to use the example configuration from the `cibuildwheel`  docs, but it doesn't seem to be tailored for arm.

**Comment by odidev** [comment]
@jlaine I will take a look at this.

**Comment by jlaine** [comment]
Closing in favor of #35

**Pull request closed without merging**
