### PR TITLE
 Use the version of msys2 included in the runner

### PR DESCRIPTION
**Pull request by JoeSchiff**
I have been getting this error on the Windows runner:
` ERROR: aom >= 2.0.0 not found using pkg-config`

I think it is because the paths in PKG_CONFIG_PATH are getting messed up.

ffbuild/config.log says:
`Can't find >=.pc in any of /c/cibw/vendor/lib/pkgconfig C \cibw\vendor\lib\pkgconfig;D \a\_temp\msys64\mingw64\lib\pkgconfig;D \a\_temp\msys64\mingw64\share\pkgconfig /usr/lib/pkgconfig /usr/share/pkgconfig`

### CODE REVIEW

**Comment by JoeSchiff** [comment]
I got the builds to pass in my fork. I'm just waiting for some more tests to finish. I'll have more info tomorrow

**Comment by JoeSchiff** [comment]
I'm still testing environ variables.

msys2 `release: false`. Build passes with:
`'PKG_CONFIG_PATH': '/c/cibw/vendor/lib/pkgconfig:C:\\msys64\\mingw64\\lib\\pkgconfig;C:\\msys64\\mingw64\\share\\pkgconfig' `

msys2 `release: true`. Build fails with:
`'PKG_CONFIG_PATH': '/c/cibw/vendor/lib/pkgconfig:D:\\a\\_temp\\msys64\\mingw64\\lib\\pkgconfig;D:\\a\\_temp\\msys64\\mingw64\\share\\pkgconfig'`

**Comment by JoeSchiff** [comment]
After removing the aom package from build-ffmpeg.py, the error persists, but with the dav1d package instead. When I removed dav1d, the error persists with the next package. So, I think this has nothing to do with aom. aom is just the first package listed.

**Comment by WyattBlue** [comment]
If you released this commit on my latest commit, and removed disabled aom on Windows. I'll merge this PR

**Comment by JoeSchiff** [comment]
Yeah, I removed aom only temporarily to test what would happen. My bad, I should have made that clearer.

This commit includes only what was grabbed from a `git clone` yesterday and 
```
      - uses: msys2/setup-msys2@v2
          ...
          release: false
```

**Comment by WyattBlue** [comment]
Thanks for your help! I'm going to use my commit though because it has a cleaner git history https://github.com/PyAV-Org/pyav-ffmpeg/commit/3c9f47a6542f8ce6117f8069adafaceb8544ee0f

**Pull request closed without merging**
