### PR TITLE
Add libvpx to build

### PR DESCRIPTION
**Pull request by uvjustin**

### CODE REVIEW

**Comment by jlaine** [comment]
Uhoh, this PR broke our build : https://github.com/PyAV-Org/PyAV/runs/5712431117?check_suite_focus=true, I'm going to back it out for now.

It might well be that we need a static build for vpx. I noticed that on Windows libvpx doesn't even offer a shared build.

**Comment by uvjustin** [comment]
Oh no, was looking forward to VPX support to fix an issue on another repo. Oh well!

**Comment by uvjustin** [comment]
@jlaine Actually from the tests you linked, the ubuntu builds are failing because the runners don't have libasound2. The macos builds are failing because of libvpx, but that is fixed the same way as here by adding the CIBW_REPAIR_WHEEL_COMMAND_MACOS command. I'll make that small PR over there now.

**Comment by jlaine** [comment]
We should not have to mess with the repair command all over the place just for the sake of cmake, could you try to debug why this is even needed?

**Comment by uvjustin** [comment]
Sure, looking into it now.

**Pull request merged**
