### PR TITLE
Fix build failures

### PR DESCRIPTION
**Pull request by jlaine**

### CODE REVIEW

**Comment by jlaine** [comment]
@uvjustin I really have no idea why we are getting this new error. It's hard enough getting all this software to build, but it's annoying as hell that with zero changes something mysteriously breaks.

I had a look and the Windows version used by GitHub Actions seems unchanged, not sure what other components were updated behind our back.

**Comment by uvjustin** [comment]
> It's hard enough getting all this software to build, but it's annoying as hell that with zero changes something mysteriously breaks.

I very much agree with your sentiments.

**Comment by jlaine** [comment]
@uvjustin the plot thickens. I downloaded the built ffmpeg onto a Windows VM, and both "ffprobe" and "ffmpeg" work fine, so I'm not convinced there is actually anything wrong with the FFmpeg libraries we build..

**Comment by jlaine** [comment]
> So...disable the tests? 😄

I'm pretty sure this will trickle down to the PyAV builds if we don't get to the bottom of it. I'm wondering if the build environment for the Python code has changed..

**Pull request merged**
